---
title: "R Notebook"
output: html_notebook
---
# FUNCIONES

# Una función es un conjunto de comandos organizados para realizar una tarea específica.

#################################

## SINTAXIS

#  SUMAR <- function (arg1, arg2)
#   {
#      Cuerpo de la funcion

#      salida <- arg1 + arg2

#      return (salida)

        # La funcion return() sirve para indicar la salida de las            funciones
#   }

#   La función se define como si fuera cualquier variable, con el operador de asignación: <-. Después viene la palabra "function", que le indica a R que se trata de una función. Lo siguiente son los argumentos, definidos entre paréntesis y separados por comas. Por último, entre corchetes está el cuerpo y la salida de la función, pueden ser una o varias líneas de código.

#   La función anterior tiene nombre, argumentos, cuerpo y salida. El nombre de la función es SUMAR. Los argumentos se llaman "arg1" y "arg2" y son sumados dentro del cuerpo. La suma se guarda en la variable llamada "salida", que, precisamente será la salida de la función.

#   De esta forma, si queremos usar nuestra función para sumar dos números, lo haríamos de la siguiente manera:

# SUMAR(4,6)

# El resultado seria el siguiente

# [1] 10

############################

## ARGUMENTOS

# Vamos a definir una función que calcule potencias. Tendrá dos argumentos, el primero será el número base, y el segundo el exponente. Lo haremos de la siguiente manera:

#   potencia <- function (base, exponente)
#    {
#       salida <- base^exponente
#       return(salida)
#    }

#   Cuando se llame a la función, se deben especificar ambos números (base y exponente). Se puede hacer especificando los valores de cada argumento:



#   potencia(2, 8)
#   potencia(base = 2, exponente = 8)
#   potencia(exponente = 8, base = 2)

#  Todos los comandos darán el mismo resultado


# FAMILIA APPLY

#   El comando apply en R permite aplicar una función a través de una matriz, array o data frame.


## SINTAXIS

#   apply(X, MARGIN, FUN)

#     X       Array, matriz o data frame
#     MARGIN  1: filas, 2: columnas, c(1, 2): filas y columnas
#     FUN     Función a ser aplicada


#  mi_matriz <- matrix(1:9,nrow = 3, ncol = 3)
#  mi_matriz
#     [,1] [,2] [,3]
# [1,]    1    4    7
# [2,]    2    5    8
# [3,]    3    6    9

# apply(mi_matriz,2,sum)
# [1]  6 15 24


##  Lapply

#   Se diferencia con apply en que opera con listas. Recibe una lista y devuelve una lista

# A <- matrix(1:9,nrow = 3, ncol = 3)
# B <- matrix(11:19,nrow = 3, ncol = 3)
# C <- matrix(21:29,nrow = 3, ncol = 3)
# mi_lista <- list(A,B,C)
# lapply(mi_lista,"[",1,1)

# [[1]]
# [1] 1

# [[2]]
# [1] 11

# [[3]]
# [1] 21


## Sapply

#  Se diferencia con apply en que opera con listas. Recibe una lista y devuelve un vector

#  sapply(mi_lista,"[",1,1)
#  [1]  1 11 21


#  Vapply
#  Devuelve un vector con la longitud que tiene cada una de las listas introducidas como parámetro.


# x <- list(A = 1, B = 1:3, C = 1:7)
# x
# $a
# [1] 1
# $b
# [1] 1 2 3
# $c
# [1] 1 2 3 4 5 6 7

# vapply(x, FUN = length, FUN.VALUE = 0L)
# a b c 
# 1 3 7

